#' Find any errors (or warnings) from a targets workflow
#' 
#' i.e. from the logs generated by setting
#' `options_local = crew_options_local(log_directory = blah)` in
#' `crew::crew_controller_local()`
#'
#' @param store Store in which the logs are being saved
#' @param days Numeric. To limit results to only the last `days` days.
#' @param warn Logical. Search for warnings?
#' @param err Logical. Search for errors?
#'
#' @returns
#' @export
#'
#' @examples
find_log_errors <- function(store
                            , days = NULL
                            , warn = FALSE
                            , err = TRUE
                            ) {
  
  logs <- fs::dir_info(store
                       , recurse = TRUE
                       , regexp = "\\.log$"
                       ) |>
    dplyr::mutate(diff = as.numeric(difftime(Sys.time(), modification_time, units = "days")))
  
  if(!is.null(days)) logs <- logs |>
      dplyr::filter(diff <= days)
  
  logs <- logs |>
    dplyr::select(path, modification_time) |>
    dplyr::mutate(log = purrr::map(path, readLines, warn = FALSE)
                  , warning = purrr::map_lgl(log
                                             , \(x) any(grepl("log", tolower(x)))
                                             )
                  , error = purrr::map_lgl(log
                                           , \(x) any(grepl("error", tolower(x)))
                                           )
                  )
  
  warn_res <- if(warn) logs |>
    dplyr::filter(warning) else tibble::tibble()
  
  err_res <- if(err) logs |>
      dplyr::filter(error) else tibble::tibble()
  
  return(dplyr::bind_rows(warn_res, err_res) |> dplyr::distinct())
  
}
